language: python
python:
  - "2.7"
  - "2.6"

install:
  - "pip install coveralls"
  - "pip install nose-cov"
  - "pip install unittest2"
  - ./test/setup_module_test.sh
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors -r requirements-py26.txt ; fi

script:
  - cd ~/shinken/test
  - export PYTHONPATH=~/shinken
  - nosetests -vx --process-restartworker  --processes=1 --process-timeout=1800
  - coverage combine

after_success:
  coveralls

notifications:
  email: false
